import type { Metadata } from "next";
import { Inter, Stack_Sans_Notch } from "next/font/google";
import "./globals.css";

const stackSans = Stack_Sans_Notch({
  variable: "--font-stack-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${stackSans.variable} ${inter.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
